# --------------------------------------------- #
# Author: ADAM - +91-9739110917                 #
# Org: Wezva Technologies                       #
# Ansible role to install JDK17, Git & Maven    #
# --------------------------------------------- #

  - name: Apt Update
    apt: update_cache=yes
  - name : Install JRE, npm & Git
    apt: name={{item}} state=present
    loop:
    - git
    - openjdk-17-jre
    - npm
